// lib/languages.ts
export const LANGUAGES = {
  en: {
    languages: "Languages",
    welcome: "Welcome",
    signIn: "Sign In",
    signOut: "Sign Out",
    settings: "Settings",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    manageAccounts: "Manage Accounts",
    trackExpenses: "Track Expenses",
    viewInsights: "View Insights",

    // WelcomeScreen translations
    appName: "Qoondeeye",
    tagline:
      "Take control of your financial future with smart money management",
    description:
      "Track expenses, manage budgets, and achieve your financial goals",
    expenseTracking: "Expense Tracking",
    accountSecurity: "Account Security",
    instantInsights: "Instant Insights",
    startManaging: "Start Managing",

    // InputCategoriesScreen translations
    accountSetup: "Account Setup",
    accountSetupDescription:
      "Choose what you want to manage — accounts, expenses, and more",
    continue: "Continue",
    includes: "Includes:",
    accounts: "Accounts",
    accountsDescription: "Cash, bank, cards, and savings balances",
    expenses: "Expenses",
    expensesDescription: "Daily spending, bills, and recurring payments",
    insights: "Insights",
    insightsDescription: "Budgets, goals, and financial reports",
    cash: "Cash",
    bank: "Bank",
    cards: "Cards",
    savings: "Savings",
    food: "Food",
    rent: "Rent",
    bills: "Bills",
    subscriptions: "Subscriptions",
    budgets: "Budgets",
    goals: "Goals",
    reports: "Reports",
    trends: "Trends",

    // AuthGateScreen translations
    takeControlOfMoney: "Take Control of Your Money",
    simpleToolsDescription:
      "Simple tools to track spending, accounts, and savings",
    allFinancesDescription:
      "All your finances in one place — secure and private",
    clearReports: "Clear Reports",
    clearReportsDescription: "See where your money goes with easy breakdowns",
    helpfulAlerts: "Helpful Alerts",
    helpfulAlertsDescription: "Stay on top of bills and daily spending",
    smartInsights: "Smart Insights",
    smartInsightsDescription: "Discover trends and plan your savings goals",
    signIn: "Sign In",
    newToMoneyManager: "New to Money Manager?",
    createAccount: "Create Account",
    helpingUsersText: "Helping users manage money securely every day",

    // LoginScreen translations
    welcomeBack: "Welcome Back",
    signInDescription: "Sign in to access your financial management dashboard",
    emailAddress: "Email Address",
    enterYourEmail: "Enter your email",
    password: "Password",
    enterYourPassword: "Enter your password",
    enterYourConfirmPassword: "Enter your confirm password",
    signingIn: "Signing In...",
    signIn: "Sign In",
    or: "OR",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    error: "Error",
    missingCredentials: "Missing credentials or invalid email/password",
    success: "Success",
    loginSuccessfully: "Login successfully",
    loginError: "Login Error",

    // SignupScreen translations
    createAccount: "Create Account",
    signupDescription: "Enter your email and create a secure password",
    fullName: "Full Name",
    enterYourFullName: "Enter your full name",
    confirmPassword: "Confirm Password",
    passwordRequirements: "Password must contain:",
    atLeast8Characters: "At least 8 characters",
    oneUppercaseLetter: "One uppercase letter",
    oneNumber: "One number",
    or: "OR",
    continueWithGoogle: "Continue with Google",
    continueWithGithub: "Continue with Git Hub",
    creatingAccount: "Creating Account...",
    signUp: "Sign Up",
    accountCreation: "Account Creation",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign In",
    passwordsDoNotMatch: "Passwords do not match",
    accountCreated: "Account created!",
    defaultAccountCreated:
      "Default account 'Account 1' has been created for you",
    pleaseCheckEmail: "Please check your email to verify your account",
    signupFailed: "Signup failed",
    pleaseFillAllFields: "Please fill in all required fields",
    fullNameCannotBeNumbers: "Full name cannot contain only numbers",
    invalidEmailFormat: "Invalid email format",
    passwordRequirementsError:
      "Password must be at least 8 characters, contain an uppercase letter, and a number",
    fullNameAlreadyTaken: "Full name already taken",
    emailAlreadyRegistered: "Email already registered",
    socialSignupFailed: "Social signup failed.",

    // DashboardScreen translations
    recentTransactions: "Recent Transactions",
    seeMore: "See More",
    noTransactionsForMonth: "No transactions for this month",
    historyExpenses: "History Expenses",
    generateReport: "Generate Report",
    compareExpenses: "Compare Expenses",

    // ProfileScreen translations
    profile: "Profile",
    contactInformation: "Contact Information",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    emailAddress: "Email Address",
    noNameProvided: "No name provided",
    noPhoneProvided: "No phone provided",
    security: "Security",
    changePassword: "Change Password",
    updateAccountPassword: "Update your account password",
    signOut: "Sign out",
    loading: "Loading...",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    enterCurrentPassword: "Enter current password",
    enterNewPassword: "Enter new password",
    confirmNewPasswordPlaceholder: "Confirm new password",
    passwordRequirements: "Password Requirements:",
    atLeast8Characters: "At least 8 characters",
    oneUppercaseLetter: "One uppercase letter",
    oneNumber: "One number",
    updating: "Updating...",
    updatePassword: "Update Password",
    error: "Error",
    success: "Success",
    failedToFetchProfile: "Failed to fetch profile data",
    userNotAuthenticated: "User not authenticated",
    profileUpdatedSuccessfully: "Profile updated successfully",
    failedToUpdateProfile: "Failed to update profile",
    nameUpdatedSuccessfully: "Name updated successfully",
    failedToUpdateName: "Failed to update name",
    phoneUpdatedSuccessfully: "Phone updated successfully",
    failedToUpdatePhone: "Failed to update phone",
    emailUpdatedSuccessfully: "Email updated successfully",
    failedToUpdateEmail: "Failed to update email",
    pleaseFillAllFields: "Please fill in all fields",
    passwordRequirementsNotMet: "Password Requirements Not Met",
    yourPasswordMustContain: "Your password must contain:",
    newPasswordsDontMatch: "New passwords don't match",
    newPasswordMustBeDifferent:
      "New password must be different from current password",
    passwordUpdatedSuccessfully: "Password updated successfully",
    failedToUpdatePassword: "Failed to update password. Please try again.",
    currentPasswordIncorrect: "Current password is incorrect",

    // UpdateProfileScreen translations
    updateProfile: "Update Profile",
    saving: "Saving...",
    save: "Save",
    tapToChangePhoto: "Tap to change your profile photo",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    enterYourFullName: "Enter your full name",
    enterYourPhoneNumber: "Enter your phone number",
    includeCountryCode: "Include country code (e.g., +1 555 123 4567)",
    profileInfoEncrypted:
      "Your profile information is encrypted and stored securely. We never share your personal data with third parties.",
    changeProfilePhoto: "Change Profile Photo",
    chooseAnOption: "Choose an option",
    cancel: "Cancel",
    takePhoto: "Take Photo",
    chooseFromLibrary: "Choose from Library",
    removePhoto: "Remove Photo",
    discardChanges: "Discard Changes",
    unsavedChangesMessage:
      "You have unsaved changes. Are you sure you want to go back?",
    keepEditing: "Keep Editing",
    discard: "Discard",
    fullNameRequired: "Full name is required",
    fullNameMinLength: "Full name must be at least 2 characters",
    emailRequired: "Email is required",
    validEmailAddress: "Please enter a valid email address",
    phoneRequired: "Phone number is required",
    validPhoneNumber: "Please enter a valid phone number",
    youNeedToBeLoggedIn: "You need to be logged in to update your profile",
    failedToFetchUser: "Failed to fetch user data",
    userNotAuthenticated: "User not authenticated",
    profileUpdatedSuccessfully: "Profile updated successfully!",
    ok: "OK",
    failedToUpdateProfile: "Failed to update profile. Please try again.",
    failedToUploadImage: "Failed to upload image",
    failedToPickImage: "Failed to pick image",

    // Accounts screen
    accounts: "Accounts",
    addAccount: "Add Account",
    assets: "Assets",
    liabilities: "Liabilities",
    total: "Total",
    cash: "Cash",
    simCard: "SIM Card",
    debitCard: "Debit Card",
    savings: "Savings",
    topup: "Top-Up/Prepaid",
    investments: "Investments",
    overdrafts: "Overdrafts",
    loan: "Loan",
    insurance: "Insurance",
    card: "Card",
    others: "Others",

    // Add Account component
    accountType: "Account Type",
    selectGroup: "Select Account Type",
    name: "Name",
    accountName: "Account name",
    amount: "Amount",
    description: "Description",
    optionalDescription: "Optional description",
    saveAccount: "Save Account",

    // Account Details page
    deleteAccount: "Delete Account",
    deleteAccountConfirm: "Are you sure you want to delete",
    deleteAccountWarning:
      "This action cannot be undone and will also delete all associated transactions, transfers, and budgets.",
    cancel: "Cancel",
    delete: "Delete",
    error: "Error",
    failedToDeleteBudgets: "Failed to delete account budgets",
    failedToDeleteTransfersFrom: "Failed to delete transfers from account",
    failedToDeleteTransfersTo: "Failed to delete transfers to account",
    failedToDeleteTransactions: "Failed to delete account transactions",
    failedToDeleteAccount: "Failed to delete account",
    success: "Success",
    accountDeletedSuccessfully: "Account deleted successfully",
    ok: "OK",
    unexpectedError: "An unexpected error occurred",
    editAccount: "Edit Account",
    currentBalance: "Current Balance",
    income: "Income",
    expense: "Expense",
    balance: "Balance",
    recentTransactions: "Recent Transactions",
    refreshing: "Refreshing...",
    refresh: "Refresh",
    refreshingTransactions: "Refreshing transactions...",
    noTransactionsYet: "No transactions yet",
    noDescription: "No description",

    // Edit Account page
    group: "Select Account Type",
    failedToLoadAccount: "Failed to load account data",
    pleaseFillRequiredFields: "Please fill in all required fields",
    failedToUpdateAccount: "Failed to update account",
    loadingAccount: "Loading account...",
    accountNotFound: "Account not found",
    updating: "Updating...",
    updateAccount: "Update Account",

    // AddExpense component
    add_transaction: "Add Transaction",
    saving: "Saving...",
    save: "Save",
    how_much: "How much?",
    choose_category: "Choose Category",
    select_category: "Select a category",
    payment_method: "Payment Method",
    select_payment_method: "Select payment method",
    whats_this_for: "What's this for?",
    add_note_about_transaction: "Add a note about this transaction...",
    select_account: "Select Account",
    when: "When?",
    transfer: "Transfer",
    transferMoney: "Transfer Money",
    moveFundsBetweenAccounts: "Move funds between your accounts",
    howMuchDoYouWantToTransfer: "How much do you want to transfer?",
    from: "From",
    to: "To",
    available: "Available",
    current: "Current",
    swapAccounts: "Swap Accounts",
    transferPreview: "Transfer Preview",
    newBalance: "new balance",
    processingTransfer: "Processing Transfer...",
    completeTransfer: "Complete Transfer",
    insufficientFunds: "Insufficient funds",
    transferReady: "Transfer ready",
    selectCategory: "Select Category",
    selectPaymentMethod: "Select Payment Method",
    select: "Select",
    account: "Account",
    repeatThis: "Repeat this?",
    howOften: "How often?",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    addNoteAboutIncome: "Add a note about this income...",

    // Income and Expense Categories
    foodAndDrinks: "Food & Drinks",
    homeAndRent: "Home & Rent",
    travel: "Travel",
    bills: "Bills",
    fun: "Fun",
    health: "Health",
    shopping: "Shopping",
    learning: "Learning",
    personalCare: "Personal Care",
    insurance: "Insurance",
    loans: "Loans",
    gifts: "Gifts",
    donations: "Donations",
    vacation: "Vacation",
    pets: "Pets",
    children: "Children",
    subscriptions: "Subscriptions",
    gymAndSports: "Gym & Sports",
    electronics: "Electronics",
    furniture: "Furniture",
    repairs: "Repairs",
    taxes: "Taxes",
    jobSalary: "Job Salary",
    bonus: "Bonus",
    partTimeWork: "Part-time Work",
    business: "Business",
    investments: "Investments",
    bankInterest: "Bank Interest",
    rentIncome: "Rent Income",
    sales: "Sales",
    gambling: "Gambling",
    awards: "Awards",
    refunds: "Refunds",
    freelance: "Freelance",
    royalties: "Royalties",
    grants: "Grants",
    giftsReceived: "Gifts Received",
    pension: "Pension",

    // Payment Methods
    cash: "Cash",
    evcPlus: "EVC Plus",
    creditCard: "Credit Card",
    debitCard: "Debit Card",
    mobileMoney: "Mobile Money",

    // Frequency Options
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",

    // Additional Alert Messages
    missingInfo: "Missing Info",
    pleaseFillRequiredFields: "Please fill in the amount and description",
    selectAccount: "Select Account",
    pleaseSelectAccount: "Please select an account",
    pleaseSelectCategoryForIncome: "Please select a category for income",
    pleaseSelectCategoryForExpense: "Please select a category for expense",
    pleaseSelectPaymentMethodForExpense:
      "Please select a payment method for expense",
    selectAccounts: "Select Accounts",
    pleaseSelectBothAccountsForTransfer:
      "Please select both from and to accounts for transfer",
    invalidTransfer: "Invalid Transfer",
    fromAndToAccountsMustBeDifferent: "From and to accounts must be different",
    yourAccountDoesntHaveEnoughBalance: "Your",
    forThisExpense: "account doesn't have enough balance for this expense",
    failedToLoadAccounts: "Failed to load accounts",
    somethingWentWrongPleaseTryAgain: "Something went wrong. Please try again.",
    pleaseEnterValidTransferAmount: "Please enter a valid transfer amount",
  },

  so: {
    languages: "Luuqada",
    welcome: "Soo dhowow",
    signIn: "Gali",
    signOut: "Ka bax",
    settings: "Dejinta",
    darkMode: "Hab Madoow",
    lightMode: "Hab Cad",
    manageAccounts: "Maamul Xisaabaadka",
    trackExpenses: "La soco Kharashaadka",
    viewInsights: "Eeg Falanqaynta",

    // WelcomeScreen translations
    appName: "Qoondeeye",
    tagline:
      "Maamul lacagtaaga mustaqbalka adoo isticmaalaya maamul lacag oo caqliga ah",
    description:
      "La soco kharashaadka, maamul miisaaniyada, oo gaadhada hadafyada lacagtaaga",
    expenseTracking: "La soco Kharashaadka",
    accountSecurity: "Amniga Xisaabka",
    instantInsights: "Fahanka Degdeg ah",
    startManaging: "Bilow Maamulka",

    // InputCategoriesScreen translations
    accountSetup: "Dejinta Xisaabka",
    accountSetupDescription:
      "Dooro waxa aad rabto inaad maamusho — xisaabaadka, kharashaadka, iyo wax kale",
    continue: "Sii wad",
    includes: "Waxay ku jiraan:",
    accounts: "Xisaabaadka",
    accountsDescription: "Lacag caddaan, bangiga, kaarka, iyo kaydka",
    expenses: "Kharashaadka",
    expensesDescription:
      "Kharash maalin kasta, biilka, iyo lacag bixinta joogtada ah",
    insights: "Fahanka",
    insightsDescription: "Miisaaniyada, hadafyada, iyo warbaahinta lacagta",
    cash: "Lacag Caddaan",
    bank: "Bangiga",
    cards: "Kaarka",
    savings: "Kayd",
    food: "Cuntada",
    rent: "Kireysiga",
    bills: "Biilka",
    subscriptions: "Dib u booqashada",
    budgets: "Miisaaniyada",
    goals: "Hadafyaadka",
    reports: "Warbaahinta",
    trends: "Dhaqdhaqaaqa",

    // AuthGateScreen translations
    takeControlOfMoney: "Maamul Lacagtaaga",
    simpleToolsDescription:
      "Qalab fudud oo loogu talagalay in la socdo kharashaadka, xisaabaadka, iyo kaydka",
    allFinancesDescription:
      "Dhammaan lacagtaaga meel hal ah — amni ah oo sir ah",
    clearReports: "Warbaahin Cad",
    clearReportsDescription:
      "Eeg halka uu aaday lacagtaaga iyadoo la isticmaalayo qaybinta fudud",
    helpfulAlerts: "Digniin Caawimaad",
    helpfulAlertsDescription: "La soco biilka iyo kharashaadka maalin kasta",
    smartInsights: "Fahanka Caqliga ah",
    smartInsightsDescription: "Hel dhaqdhaqaaqa oo qorsheeyada kaydkaaga",
    signIn: "Gali",
    newToMoneyManager: "Cusub Maamulka Lacagta?",
    createAccount: "Abuur Xisaab",
    helpingUsersText:
      "Kaaga caawinaya in la maamulo lacagta si amni ah maalin kasta",

    // LoginScreen translations
    welcomeBack: "Soo dhowow",
    signInDescription: "Gali si aad u hesho dashboardka maamulka lacagtaaga",
    emailAddress: "Cinwaanka Emailka",
    enterYourEmail: "Geli emailkaaga",
    password: "Furaha",
    enterYourPassword: "Geli furahaaga",
    enterYourConfirmPassword: "Geli furahaaga mar labaad",
    signingIn: "Galinaya...",
    signIn: "Gali",
    or: "AMA",
    dontHaveAccount: "Ma haysataa xisaab?",
    signUp: "Abuur Xisaab",
    error: "Khalad",
    missingCredentials: "Furaha ma jira ama email/furaha khaldan",
    success: "Guul",
    loginSuccessfully: "Gelitaanka guulay",
    loginError: "Khaladka Galitaanka",

    // SignupScreen translations
    createAccount: "Abuur Xisaab",
    signupDescription: "Geli emailkaaga oo abuur furaha amni ah",
    fullName: "Magaca Buuxa",
    enterYourFullName: "Geli magacaaga buuxa",
    confirmPassword: "Xaqiiji Furaha",
    passwordRequirements: "Furaha waa inay ku jiraan:",
    atLeast8Characters: "Ugu yaraan 8 xaraf",
    oneUppercaseLetter: "Hal xaraf weyn",
    oneNumber: "Hal tiro",
    or: "AMA",
    continueWithGoogle: "Sii wad Google",
    continueWithGithub: "Sii wad Git Hub",
    creatingAccount: "Abuuritaanka Xisaabka...",
    signUp: "Abuur Xisaab",
    accountCreation: "Abuuritaanka Xisaabka",
    alreadyHaveAccount: "Horey u haysataa xisaab?",
    signIn: "Gali",
    passwordsDoNotMatch: "Furaha ma isku mid aha",
    accountCreated: "Xisaabka waa la abuuray!",
    defaultAccountCreated: "Xisaabka caadiga ah 'Account 1' ayaa laguu abuuray",
    pleaseCheckEmail: "Fadlan hubi emailkaaga si aad u xaqiijiso xisaabkaaga",
    signupFailed: "Abuuritaanka xisaabka waa la fashilay",
    pleaseFillAllFields: "Fadlan buuxi dhammaan goobaha loo baahan yahay",
    fullNameCannotBeNumbers: "Magaca buuxa ma noqon karo tiro kaliya",
    invalidEmailFormat: "Qaabka emailka waa khaldan",
    passwordRequirementsError:
      "Furaha waa inay ahaataan ugu yaraan 8 xaraf, ay ku jiraan xaraf weyn, iyo tiro",
    fullNameAlreadyTaken: "Magaca buuxa horey u la qaaday",
    emailAlreadyRegistered: "Emailka horey u la diiwaangeliyay",
    socialSignupFailed: "Abuuritaanka bulshada waa la fashilay.",

    // DashboardScreen translations
    recentTransactions: "Dhaqdhaqaaqaaga",
    seeMore: "Eeg Dheeraad",
    noTransactionsForMonth: "Macamiisho ma jiraan bishan",
    historyExpenses: "Taariikhda Kharashaadka",
    generateReport: "Soo saar Warbaahin",
    compareExpenses: "Isku barbar dhig Kharashaadka",

    // ProfileScreen translations
    profile: "Profile",
    contactInformation: "Macluumaadka Xiriirka",
    fullName: "Magaca Buuxa",
    phoneNumber: "Telefoonka",
    emailAddress: "Cinwaanka Emailka",
    noNameProvided: "Magac ma la bixin",
    noPhoneProvided: "Telefoon ma la bixin",
    security: "Amniga",
    changePassword: "Beddel Furaha",
    updateAccountPassword: "Cusboonaysii furaha akoonkaaga",
    signOut: "Ka bix",
    loading: "Waa la soo dejinayaa...",
    currentPassword: "Furaha Hadda",
    newPassword: "Furaha Cusub",
    confirmNewPassword: "Xaqiiji Furaha Cusub",
    enterCurrentPassword: "Geli furaha hadda",
    enterNewPassword: "Geli furaha cusub",
    confirmNewPasswordPlaceholder: "Xaqiiji furaha cusub",
    passwordRequirements: "Shuruudaha Furaha:",
    atLeast8Characters: "Ugu yaraan 8 xaraf",
    oneUppercaseLetter: "Hal xaraf weyn",
    oneNumber: "Hal tiro",
    updating: "Waa la cusboonaynayaa...",
    updatePassword: "Cusboonaysii Furaha",
    error: "Khalad",
    success: "Guul",
    failedToFetchProfile: "Furaha profile-ka waa la fashilay",
    userNotAuthenticated: "Isticmaalaha ma la xaqiijin",
    profileUpdatedSuccessfully:
      "Profile-ka si guul leh ayaa loo cusboonaysiiyay",
    failedToUpdateProfile: "Profile-ka cusboonaysiinta waa la fashilay",
    nameUpdatedSuccessfully: "Magaca si guul leh ayaa loo cusboonaysiiyay",
    failedToUpdateName: "Magaca cusboonaysiinta waa la fashilay",
    phoneUpdatedSuccessfully: "Telefoonka si guul leh ayaa loo cusboonaysiiyay",
    failedToUpdatePhone: "Telefoonka cusboonaysiinta waa la fashilay",
    emailUpdatedSuccessfully: "Emailka si guul leh ayaa loo cusboonaysiiyay",
    failedToUpdateEmail: "Emailka cusboonaysiinta waa la fashilay",
    pleaseFillAllFields: "Fadlan buuxi dhammaan meelaha",
    passwordRequirementsNotMet: "Shuruudaha Furaha Lama Buuxin",
    yourPasswordMustContain: "Furahaagu waa inuu ka kooban yahay:",
    newPasswordsDontMatch: "Furaha cusub ma isku mid aha",
    newPasswordMustBeDifferent:
      "Furaha cusub waa inuu ka duwan yahay kan hadda",
    passwordUpdatedSuccessfully: "Furaha si guul leh ayaa loo cusboonaysiiyay",
    failedToUpdatePassword:
      "Furaha cusboonaysiinta waa la fashilay. Fadlan isku day mar kale.",
    currentPasswordIncorrect: "Furaha hadda waa khaldan",

    // UpdateProfileScreen translations
    updateProfile: "Cusboonaysii Profile-ka",
    saving: "Waa la kaydinayaa...",
    save: "Kaydi",
    tapToChangePhoto: "Riix si aad u beddesho sawirka profile-kaaga",
    fullName: "Magaca Buuxa",
    emailAddress: "Cinwaanka Emailka",
    phoneNumber: "Telefoonka",
    enterYourFullName: "Geli magacaaga buuxa",
    enterYourPhoneNumber: "Geli telefoonkaaga",
    includeCountryCode: "Ku dar koodka dalalka (tusaale, +252 61 123 4567)",
    profileInfoEncrypted:
      "Macluumaadka profile-kaaga waa la xifdiyay oo la kaydiyay si amni ah. Ma na sahayno macluumaadkaaga shakhsi ah maamulayaal kale.",
    changeProfilePhoto: "Beddel Sawirka Profile-ka",
    chooseAnOption: "Dooro doorasho",
    cancel: "Jooji",
    takePhoto: "Qaab Sawir",
    chooseFromLibrary: "Dooro ka Library-ga",
    removePhoto: "Ka saar Sawirka",
    discardChanges: "Ka saar Isbedelada",
    unsavedChangesMessage:
      "Waxaad haysataa isbedelada aan la kaydin. Ma hubtaa inaad aadka u noqon doonto?",
    keepEditing: "Sii wax ka beddel",
    discard: "Ka saar",
    fullNameRequired: "Magaca buuxa waa la baahan yahay",
    fullNameMinLength: "Magaca buuxa waa inuu ahaadaa ugu yaraan 2 xaraf",
    emailRequired: "Email waa la baahan yahay",
    validEmailAddress: "Fadlan geli cinwaan email ah oo sax ah",
    phoneRequired: "Telefoonka waa la baahan yahay",
    validPhoneNumber: "Fadlan geli telefoon ah oo sax ah",
    youNeedToBeLoggedIn:
      "Waxaad u baahan tahay inaad gasho si aad u cusboonaysiiso profile-kaaga",
    failedToFetchUser: "Isticmaalaha macluumaadka waa la fashilay",
    userNotAuthenticated: "Isticmaalaha ma la xaqiijin",
    profileUpdatedSuccessfully:
      "Profile-ka si guul leh ayaa loo cusboonaysiiyay!",
    ok: "Hagaag",
    failedToUpdateProfile:
      "Profile-ka cusboonaysiinta waa la fashilay. Fadlan isku day mar kale.",
    failedToUploadImage: "Sawirka soo dejinta waa la fashilay",
    failedToPickImage: "Sawirka doorashada waa la fashilay",

    // Accounts screen
    accounts: "Xisaabaadka",
    addAccount: "Ku dar Xisaab",
    assets: "Hantida",
    liabilities: "Deymaha",
    total: "Wadar",
    cash: "Lacag Caddaan",
    simCard: "SIM Card",
    debitCard: "Kaarka Xisaabta.",
    savings: "Kayd",
    topup: "kudarid lacag",
    investments: "Maalgelin",
    overdrafts: "Deen Kasoo qadatay bankiga",
    loan: "Amaah",
    insurance: "Caymis",
    card: "Kaarka",
    others: "Qaab kale",

    // Add Account component
    accountType: "Nooca Xisaabka",
    selectGroup: "Dooro akoonkaaga",
    name: "Magaca",
    accountName: "Magaca akoonkaaga",
    amount: "Lacagta",
    description: "Faahfaahin",
    optionalDescription: "Faahfaahin aad dooran karto",
    saveAccount: "Kaydi Xisaabka",

    // Account Details page
    deleteAccount: "Ka saar Xisaab",
    deleteAccountConfirm: "Ma hubtaa inaad ka saar",
    deleteAccountWarning:
      "Ficilkani lama celin karo wuxuuna sidoo kale tirtiri doonaa dhammaan Dhaqdhaqaaqaaga, wareejintada , iyo miisaaniyadaha la xiriira",
    cancel: "Jooji",
    delete: "Ka saar",
    error: "Khalad",
    failedToDeleteBudgets: "Xisaabaadka miisaaniyada waa la fashilay",
    failedToDeleteTransfersFrom: "Xisaabaadka kharashaadka waa la fashilay",
    failedToDeleteTransfersTo: "Xisaabaadka kharashaadka waa la fashilay",
    failedToDeleteTransactions: "Xisaabaadka kharashaadka waa la fashilay",
    failedToDeleteAccount: "Xisaabaadka waa la fashilay",
    success: "Guul",
    accountDeletedSuccessfully: "Xisaabaadka si guul leh ayaa loo dibay!",
    ok: "Hagaag",
    unexpectedError: "Wuxuu u dib u dibay inaad ku dibay",
    editAccount: "Beddel Xisaab",
    currentBalance: "Lacagta Wadarta Hadda.",
    income: "Dakhligaga Kusoo galay.",
    expense: "Kharashaadka Kaa baxay.",
    balance: "Lacagta Wadarta",
    recentTransactions: "Dhaqdhaqaaqaaga",
    refreshing: "Waa la dibinayaa...",
    refresh: "Dib",
    refreshingTransactions: "Waa la dibinayaa kharashaadka...",
    noTransactionsYet: "Ma xusuusan kharashaadka",
    noDescription: "Faahfaahin ma la bixin",

    // Edit Account page
    group: "Nooca Xisaabka",
    failedToLoadAccount: "Xisaabaadka waa la fashilay",
    pleaseFillRequiredFields: "Fadlan buuxi dhammaan goobaha loo baahan yahay",
    failedToUpdateAccount: "Xisaabaadka cusboonaysiinta waa la fashilay",
    loadingAccount: "Xisaabaadka waa la dibinayaa...",
    accountNotFound: "Xisaabaadka waa la qaaday",
    updating: "Waa la cusboonaynayaa...",
    updateAccount: "Cusboonaysii Xisaabka",

    // AddExpense component
    add_transaction: "Ku dar Dhaqdhaqaaqaaga",
    saving: "Waa la kaydinayaa...",
    save: "Kaydi",
    how_much: "Xaddiga Lacagta?",
    choose_category: "Dooro Nuuca",
    select_category: "Dooro Nuuca",
    payment_method: "Habka Bixinta Lacagta",
    select_payment_method: "Dooro Habka Bixinta Lacagta",
    whats_this_for: "Ku qor ujeeddada kooban?",
    add_note_about_transaction: "Ku dar Faahfaahin ku saabsan Dhaqdhaqaaqaaga?",
    select_account: "Dooro akoonkaaga",
    when: "Goorme?",
    transfer: "Wareejinta",
    transferMoney: "Wareejinta Lacagta",
    moveFundsBetweenAccounts: "Wareejinta lacagtaaga Akoomka",
    howMuchDoYouWantToTransfer: "Imisa lacag ayaad rabtaa inaad wareejiso?",
    from: "Ka dir ",
    to: "U dir",
    available: "Hadda la heli karo",
    current: "Wadar Hadda",
    swapAccounts: "Kala Bedel Xisaabaadka",
    transferPreview: "Hordhac wareejin",
    newBalance: "wadar hadda",
    processingTransfer: "Wareejinta way socotaa…",
    completeTransfer: "Dhameystir Wareejinta",
    insufficientFunds: "Lacag  kugu filan maku jirto",
    transferReady: "Wareejinta waa  Diyaar",
    selectCategory: "Dooro Nuuca",
    selectPaymentMethod: "Dooro Habka Bixinta Lacagta",
    select: "Dooro",
    account: "Xisaab",
    repeatThis: "Kan maku cel celin?",
    howOften: "Imisa jeer?",

    addNoteAboutIncome: "Ku dar qoraal ku saabsan dakhligan",

    // Income and Expense Categories
    foodAndDrinks: "Cuntada iyo Cabitaanka",
    homeAndRent: "Kireysiga Kaaga Baxay",
    travel: "Safar",
    bills: "Biilka",
    fun: "Madadaalo",
    health: "Caafimaad ahan",
    shopping: "Tukaameysi",
    learning: "Waxbarasho",
    personalCare: "Daryeel shaqsiyadeed",
    insurance: "Caymis",
    loans: "Amaah",
    gifts: "Hadiyad",
    donations: "Deeq / Tabaruc",
    vacation: "Safar",
    pets: "Xayawaan guri",
    children: "Caruurta",
    subscriptions: "Rukumo joogto ah",
    gymAndSports: "Jimicsi iyo Ciyaaro",
    electronics: "Korontada",
    furniture: "Qalabka Guryaha ",
    repairs: "Dayactir",
    taxes: "Canshuur",
    jobSalary: "Mushahar shaqo",
    bonus: "Gunno",
    partTimeWork: "Shaqada Maalmaha Fasaxa",
    business: "Ganacsi",
    investments: "Maalgelin",
    bankInterest: "Ribada bangiga",
    rentIncome: "Kireysiga Kusoo galay",
    sales: "Musharka",
    gambling: "Khamaar",
    awards: "Abaal-marin",
    refunds: "Lacag celin",
    freelance: "Shaqo madax-bannaan",
    royalties: "Lacagta xuquuqda",
    grants: "Deeqo Lacageed",
    giftsReceived: "Hadiyad Kusoo galay",
    pension: "Mushahar hawlgab",

    // Payment Methods
    cash: "Lacag",
    evcPlus: "EVC Plus",
    creditCard: "Kaarka Kredhka",
    debitCard: "Kaarka Xisaabta",
    mobileMoney: "Lacagta Mobileka",

    // Frequency Options
    daily: "Maalin kasta",
    weekly: "Usbuucii",
    monthly: "Bil kasta",
    yearly: "Sannad kasta",

    // Additional Alert Messages
    missingInfo: "Macluumaadka maqan",
    pleaseFillRequiredFields: "Fadlan buuxi lacagta iyo sharaxaada",
    selectAccount: "Dooro Akoonka",
    pleaseSelectAccount: "Fadlan dooro akoonka",
    pleaseSelectCategoryForIncome: "Fadlan dooro qaybta dakhliga",
    pleaseSelectCategoryForExpense: "Fadlan dooro qaybta kharashka",
    pleaseSelectPaymentMethodForExpense:
      "Fadlan dooro habka lacag bixinta kharashka",
    selectAccounts: "Dooro Akoonka",
    pleaseSelectBothAccountsForTransfer:
      "Fadlan dooro labada akoonka oo kala ah ka iyo ku",
    invalidTransfer: "Wareejin aan shaqaynayn",
    fromAndToAccountsMustBeDifferent:
      "Ka iyo ku akoonka waa inay kala duwanyihiin",
    yourAccountDoesntHaveEnoughBalance: "Akoonkaaga",
    forThisExpense: "ma laha kharashka kharashka",
    failedToLoadAccounts: "Akoonka lama soo dejin karin",
    somethingWentWrongPleaseTryAgain:
      "Waxaa dhacay khalad. Fadlan isku day mar kale.",
    pleaseEnterValidTransferAmount: "Fadlan geli lacag wareejin ah oo sax ah",
  },
};
