// lib/languages.ts
export const LANGUAGES = {
  en: {
    languages: "Languages",
    welcome: "Welcome",
    signIn: "Sign In",
    signOut: "Sign Out",
    settings: "Settings",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    manageAccounts: "Manage Accounts",
    trackExpenses: "Track Expenses",
    viewInsights: "View Insights",

    // Accounts screen
    accounts: "Accounts",
    addAccount: "Add Account",
    assets: "Assets",
    liabilities: "Liabilities",
    total: "Total",
    cash: "Cash",
    simCard: "SIM Card",
    debitCard: "Debit Card",
    savings: "Savings",
    topup: "Top-Up/Prepaid",
    investments: "Investments",
    overdrafts: "Overdrafts",
    loan: "Loan",
    insurance: "Insurance",
    card: "Card",
    others: "Others",
  },

  so: {
    languages: "Luuqada",
    welcome: "Soo dhowow",
    signIn: "Gali",
    signOut: "Ka bax",
    settings: "Dejinta",
    darkMode: "Hab Madoow",
    lightMode: "Hab Cad",
    manageAccounts: "Maamul Xisaabaadka",
    trackExpenses: "La soco Kharashaadka",
    viewInsights: "Eeg Falanqaynta",

    // Accounts screen
    accounts: "Xisaabaadka",
    addAccount: "Ku dar Xisaab",
    assets: "Hantida",
    liabilities: "Deymaha",
    total: "Wadar",
    cash: "Lacag Caddaan",
    simCard: "SIM Card",
    debitCard: "Kaarka Debit",
    savings: "Kayd",
    topup: "Lacag Kudhac/Prepaid",
    investments: "Maalgelin",
    overdrafts: "Overdrafts",
    loan: "Amaah",
    insurance: "Caymis",
    card: "Kaarka",
    others: "Kale",
  },

  ar: {
    languages: "اللغة",
    welcome: "أهلا بك",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    settings: "الإعدادات",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    manageAccounts: "إدارة الحسابات",
    trackExpenses: "تتبع النفقات",
    viewInsights: "عرض التحليلات",

    // Accounts screen
    accounts: "الحسابات",
    addAccount: "إضافة حساب",
    assets: "الأصول",
    liabilities: "الالتزامات",
    total: "الإجمالي",
    cash: "نقد",
    simCard: "شريحة SIM",
    debitCard: "بطاقة خصم",
    savings: "المدخرات",
    topup: "شحن/مسبق الدفع",
    investments: "الاستثمارات",
    overdrafts: "السحب على المكشوف",
    loan: "قرض",
    insurance: "التأمين",
    card: "بطاقة",
    others: "أخرى",
  },
};
